const API = localStorage.getItem('jobintel_api') || 'http://localhost:8100';
const nav = ['⌂ Dashboard','▣ Job Market','▤ My Applications','▤ ATS CV Check','♡ Matches','▥ Skill Gap','▧ Analytics','⚙ Settings'];
document.querySelector('#nav').innerHTML=nav.map((n,i)=>`<div class="nav ${i===0?'active':''}">${n}</div>`).join('');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const head=t=>`<div class="panelHead"><h3>${t}</h3><a>View all →</a></div>`;
function ring(v,l){return `<div class="ring" style="--v:${v*3.6}deg"><div><b>${v}%</b><small>${l}</small></div></div>`}
async function load(){
 const r=await fetch(`${API}/api/dashboard`); const d=await r.json(); const s=d.summary;
 const metrics=[['💼','Active Jobs',s.active_jobs.toLocaleString(),'↗ +12% vs last week'],['▤','New Today',s.new_today,'↗ +8% vs yesterday'],['➤','Applications',s.applications,'Manual tracking'],['👥','Interviews',s.interviews,'Your pipeline'],['🏆','Offers',s.offers,'Keep going'],['▤','ATS CV Score',`${s.ats_score} / 100`,'✓ ATS Ready']];
 document.querySelector('#metrics').innerHTML=metrics.map((m,i)=>`<div class="metric card ${i===5?'atsMini':''}"><div class="metricIcon">${m[0]}</div><div><small>${m[1]}</small><b>${m[2]}</b><span>${m[3]}</span></div></div>`).join('');
 document.querySelector('#matches').innerHTML=head('Best Current Matches')+d.matches.map(m=>`<div class="job"><div class="company">${esc(m.company).slice(0,2).toUpperCase()}</div><div class="grow"><b>${esc(m.title)}</b><small>${esc(m.company)} · ${esc(m.location)}</small><div>${m.skills.slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></div>${ring(Math.round(m.match),'AI Match')}</div>`).join('');
 const max=Math.max(...d.top_skills.map(x=>x.count),1); document.querySelector('#skills').innerHTML=head('Top Skills in Demand')+`<div class="bars">${d.top_skills.map(x=>`<div class="barItem"><span>${esc(x.skill)}</span><div><i style="width:${Math.max(10,x.count/max*100)}%"></i></div><b>${x.count}</b></div>`).join('')}</div>`;
 document.querySelector('#pipeline').innerHTML=`<div class="panelHead"><h3>Application Pipeline</h3><span class="pill info">✎ Manual tracking enabled</span></div><div class="pipeline">${['Saved','Applied','Screening','Interview','Final','Offer'].map(x=>`<div><div class="dot">${d.pipeline[x]||0}</div><small>${x}</small></div>`).join('')}</div><button id="addApp" class="primary">＋ Add application</button>`;
 document.querySelector('#ats').innerHTML=head('ATS CV Check')+`<div class="atsBody">${ring(89,'/ 100')}<div><span class="pill good">✓ ATS Ready</span><p>Your CV is well structured for machine parsing.</p></div><ul><li>✓ Format OK</li><li>✓ Keywords coverage 83%</li><li>✓ Sections complete</li><li>△ Tailor keywords per job</li></ul></div>`;
 document.querySelector('#performance').innerHTML=`<div class="panelHead"><h3>My Performance</h3><span class="tag">Last 30 days</span></div>${d.performance.map(p=>`<div class="perf"><span>${p.label}</span><div class="progress"><i style="width:${p.value}%"></i></div><b>${p.value}%</b></div>`).join('')}<div class="callout">⭐ Best performing version: Data Engineer CV v3</div>`;
 document.querySelector('#gaps').innerHTML=head('Skill Gap')+d.skill_gap.map(x=>`<div class="gap"><b>${esc(x.skill)}</b><span class="pill warn">${esc(x.priority)}</span><small>${esc(x.action)}</small></div>`).join('');
 document.querySelector('#readiness').innerHTML=head('Interview Readiness')+`<div class="ready">${ring(d.interview_readiness.score,'Ready')}<div><span class="pill good">▥ ${d.interview_readiness.level}</span><p>✓ Key skills match</p><p>✓ Relevant experience</p><p>✓ Common questions prepared</p><p>△ More system design practice</p></div></div><div class="callout">✨ Best next action: tailor your Data Engineer CV and practise system design.</div>`;
 document.querySelector('#followups').innerHTML=head('Follow-ups')+`<div class="followBig">🔔 <b>${d.followups.length}</b><span>applications need attention</span></div>`+d.followups.map(f=>`<div class="follow"><div><b>${esc(f.role)}</b><small>${esc(f.company)} · ${esc(f.status)}</small></div><span class="pill warn">Review</span></div>`).join('');
 document.querySelector('#suggestions').innerHTML=head('✨ AI Improvement Suggestions')+`<div class="suggestGrid">${d.ai_suggestions.map((x,i)=>`<div class="suggest"><div class="suggestIcon">${['◉','◎','▤','☁'][i]||'✦'}</div><b>${esc(x.title)}</b><small>${esc(x.detail)}</small></div>`).join('')}</div>`;
 document.querySelector('#addApp').onclick=()=>document.querySelector('#modal').classList.remove('hidden');
}
async function ask(){const input=document.querySelector('#chatInput'); const q=input.value.trim(); if(!q)return; input.value=''; const msgs=document.querySelector('#messages'); msgs.innerHTML+=`<div class="bubble me">${esc(q)}</div>`; const r=await fetch(`${API}/api/assistant`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})}); const j=await r.json(); msgs.innerHTML+=`<div class="bubble ai">${esc(j.answer)}</div>`; msgs.scrollTop=msgs.scrollHeight;}
document.querySelector('#sendChat').onclick=ask; document.querySelector('#chatInput').onkeydown=e=>{if(e.key==='Enter')ask()};
document.querySelector('#closeModal').onclick=()=>document.querySelector('#modal').classList.add('hidden');
document.querySelector('#appForm').onsubmit=async e=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target).entries()); f.match_score=Number(f.match_score||0); await fetch(`${API}/api/applications`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)}); document.querySelector('#modal').classList.add('hidden'); e.target.reset(); await load();};
load().catch(err=>{document.querySelector('main').innerHTML=`<div class="error"><h2>JobIntel API is unavailable</h2><p>${esc(err.message)}</p><p>Start the stack with <code>docker compose up --build</code>.</p></div>`});
